package util;

/**
 * Created by florian on 11/11/14.
 */
public enum EmailMessage {

    REGISTRATION_APP_EMAIL_TITLE,
    REGISTRATION_APP_EMAIL_BODY,
    INVITATION_EMAIL_TITLE,
    NEW_PASSWORD_EMAIL_TITLE,
    NEW_PASSWORD_EMAIL_BODY,
    INVITATION_EMAIL_BODY

}
