package util;

/**
 * Created by florian on 11/11/14.
 */
public enum ErrorMessage {

    WRONG_AUTHORIZATION,
    LOGIN_WRONG_PASSWORD_LOGIN,
    NOT_CONNECTED,
    HOME_NAME_ALREADY_USED,
    EMAIL_ALREADY_USED,
    NOT_YOU_ROOMMATE,
    ENTITY_NOT_FOUND,
    NOT_YOU_CATEGORY,
    NOT_YOU_TICKET,
    NOT_TICKET_CREATOR,
    CANNOT_REMOVE_YOURSELF,
    NOT_YOU_HOME,
    WRONG_PASSWORD,
    UNIQUE_CONSTRAIN_VIOLATION,
    CATEGORY_WITH_SAME_NAME_ALREADY_EXISTS,
    CATEGORY_USED,
    ROOMMATE_USED,
    NOT_YOU_EVENT,
    NOT_EVENT_CREATOR,
    NOT_YOU_SHOPPING_ITEM,
    NOT_ITEM_CREATOR,
    ACTIVATION_KEY_NOT_FOUND,
    DTO_NULL, DTO_NOT_EXPECTED, FATAL_ERROR,
    JSON_CONVERSION_ERROR,
    //not translate yet
    VALIDATION_SIZE,
    VALIDATION_NOT_NULL,
    DTO_VERIFICATION_PATTERN_STRING_EXPECTED, //a strign flied is expected for the pattern annotation, but th field {0} is a {1}
    VALIDATION_PATTERN,
    NOT_YOURSELF, NOT_YOUR_OLD_PASSWORD,
    LANGUAGE_NOT_ACCEPTED, NOT_YOUR_PASSWORD, UNKNOWN_EMAIL, VALIDATION_DEBTOR;

}
